"use client";
import { useEffect, useRef, useState, useSyncExternalStore, type ReactNode } from "react";
import type { ProjectStore } from "@/application";
import type { RuntimeSaveStatus } from "@/runtime/project-runtime";

export const MODULES = ["Overview", "Streams", "People", "Tasks", "Milestones", "Gantt", "Tube Map", "Risk Log", "Decision Log", "Warnings", "Search", "File Information"] as const;
export type ModuleName = (typeof MODULES)[number];
export interface NavigationTarget { readonly module: ModuleName; readonly entityId?: string; readonly requestId: number }
let nextNavigationRequestId = 0;
export const createNavigationTarget = (module: ModuleName, entityId: string | undefined, requestId = ++nextNavigationRequestId): NavigationTarget => ({ module, entityId, requestId });
export type SaveVisualState = "saved" | "dirty" | "saving" | "failed" | "lost";
export const saveStateLabel = (state: SaveVisualState, savedAt?: string) => ({ saved: `Saved${savedAt ? ` · ${savedAt}` : ""}`, dirty: "Unsaved", saving: "Saving…", failed: "Save failed", lost: "File access lost" })[state];
export function keyboardAction(event: Pick<KeyboardEvent, "key" | "metaKey" | "ctrlKey" | "shiftKey">): "save" | "undo" | "redo" | "search" | undefined {
  if (!(event.metaKey || event.ctrlKey)) return;
  const key = event.key.toLowerCase();
  if (key === "s") return "save";
  if (key === "k") return "search";
  if (key === "y" || (key === "z" && event.shiftKey)) return "redo";
  if (key === "z") return "undo";
}

export function AppShell({ store, onClose, onSave, onSaveAs, onReload, onKeepCurrent, runtimeStatus, lastSavedAt, failedSaveCount=0, message, pendingSwitch, onOpenProject, onContinueSwitch, onCancelSwitch, children }: { store?: ProjectStore; onClose: () => void | Promise<void>; onSave: () => Promise<void>; onSaveAs:()=>Promise<void>; onReload:()=>Promise<void>; onKeepCurrent:()=>Promise<void>; runtimeStatus?:RuntimeSaveStatus; lastSavedAt?:string; failedSaveCount?:number; message?:string; pendingSwitch?:boolean; onOpenProject:()=>Promise<void>; onContinueSwitch:()=>Promise<void>; onCancelSwitch:()=>void; children?: (module: ModuleName, navigate: (module: ModuleName, entityId?: string) => void, target?: NavigationTarget) => ReactNode }) {
  const [module, setModule] = useState<ModuleName>("Overview"); const [target,setTarget]=useState<NavigationTarget>(); const navigate=(next:ModuleName,entityId?:string)=>{setModule(next);setTarget(createNavigationTarget(next,entityId))}; const [collapsed, setCollapsed] = useState(false); const [operationState, setOperationState] = useState<SaveVisualState>();
  const state = useSyncExternalStore(store?.subscribe ?? (() => () => {}), store?.getState ?? (() => undefined), store?.getState ?? (() => undefined));
  const mapped:SaveVisualState|undefined=runtimeStatus==="save-failed"?"failed":runtimeStatus==="file-lost"?"lost":runtimeStatus==="dirty"?"dirty":runtimeStatus==="saved"?"saved":undefined; const saveState: SaveVisualState = operationState ?? mapped ?? (store?.isDirty() ? "dirty" : "saved"); const savedTime=lastSavedAt?new Date(lastSavedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):undefined;
  const save = async () => { if (!store?.isDirty()) return; const timer = window.setTimeout(() => setOperationState("saving"), 500); try { await onSave(); setOperationState(undefined); } catch { setOperationState("failed"); } finally { clearTimeout(timer); } };
  useEffect(() => { const handler = (event: KeyboardEvent) => { const action = keyboardAction(event); if (!action) return; event.preventDefault(); if (action === "save") void save(); if (action === "undo") store?.undo(); if (action === "redo") store?.redo(); if (action === "search") navigate("Search"); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  if (!store || !state) return <main className="launcher"><section><h1>No active project</h1><button onClick={onClose}>Return to Launcher</button></section></main>;
  return <div className={`app-shell ${collapsed ? "is-collapsed" : ""}`}>
    <aside><div className="brand">{collapsed ? "PM" : "PROJECT MANAGER"}</div><button className="collapse" aria-label="Toggle compact sidebar" onClick={() => setCollapsed(!collapsed)}>☰</button><nav aria-label="Project modules">{MODULES.map((name) => <button key={name} title={name} aria-current={module === name ? "page" : undefined} onClick={() => navigate(name)}><span>{name.slice(0, 1)}</span>{!collapsed && name}</button>)}</nav></aside>
    <div className="app-main"><header><div><p>Current project</p><strong>{state.project.name}</strong></div><div className="header-actions"><span role="status" aria-live="polite" className={`save-state ${saveState}`}>{saveStateLabel(saveState,savedTime)}</span><button className="secondary" disabled={!store.isDirty()} onClick={() => void save()}>Save Now</button><button className="icon" aria-label="Undo" disabled={!store.canUndo()} onClick={() => store.undo()}>↶</button><button className="icon" aria-label="Redo" disabled={!store.canRedo()} onClick={() => store.redo()}>↷</button><button className="search" onClick={() => navigate("Search")}>Search <kbd>⌘K</kbd></button><button className="secondary" onClick={()=>void onOpenProject()}>Open Project</button><button className="secondary" onClick={onClose}>Close</button></div></header>
      <main className="workspace">{pendingSwitch&&<div className="alert" role="alert"><strong>Save failed</strong><p>Continue and discard unsaved changes, or cancel the project switch.</p><div className="actions"><button className="danger" onClick={()=>void onContinueSwitch()}>Continue and discard</button><button className="secondary" onClick={onCancelSwitch}>Cancel</button></div></div>}{(runtimeStatus==="save-failed"||runtimeStatus==="file-lost")&&<div className="alert" role="alert"><strong>{runtimeStatus==="file-lost"?"File access lost":"Save failed"}</strong><p>{message} Your current work remains in memory.</p><div className="actions"><button onClick={()=>void save()}>Retry</button>{failedSaveCount>1&&<button className="secondary" onClick={()=>void onSaveAs()}>Save As</button>}</div></div>}{runtimeStatus==="externally-modified"&&<div className="alert" role="alert"><strong>Project file changed externally</strong><p>{message}</p><div className="actions"><button onClick={()=>void onKeepCurrent()}>Keep Current</button><button className="secondary" onClick={()=>void onReload()}>Reload from File</button></div></div>}{children ? children(module, navigate, target) : <Placeholder module={module} />}</main>
    </div>
  </div>;
}
function Placeholder({ module }: { module: ModuleName }) { return <section className="panel"><p className="eyebrow">Module</p><h1>{module}</h1><div className="empty"><strong>{module} is ready</strong><p>This module will become operational in its scheduled implementation block.</p></div></section>; }

export function Dialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { const dialog=useRef<HTMLElement>(null); useEffect(()=>{const prior=document.activeElement as HTMLElement|null;const node=dialog.current;node?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();onClose()}if(event.key==="Tab"&&node){const controls=[...node.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')];if(!controls.length)return;const first=controls[0],last=controls.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);prior?.focus()}},[onClose]); return <div className="dialog-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><h2 id="dialog-title">{title}</h2><button className="icon" aria-label={`Close ${title}`} onClick={onClose}>×</button></header>{children}</section></div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="empty"><strong>{title}</strong><p>{description}</p>{action}</div>; }
export function Status({ children }: { children: ReactNode }) { return <span className="status">{children}</span>; }
