import { EMPTY_IDENTIFIER_SEQUENCES, type LifecycleStatus, type Project } from "../../domain";
import type { ProjectState } from "../../application";

export interface ProjectDraft { name: string; description?: string; startDate: string; endDate?: string; status: LifecycleStatus }
export function validateProjectDraft(draft: ProjectDraft): Record<string, string> { const errors: Record<string, string> = {}; if (!draft.name.trim()) errors.name = "Project name is required."; if (!draft.startDate) errors.startDate = "Start date is required."; if (!draft.status) errors.status = "Status is required."; if (draft.endDate && draft.startDate && draft.startDate > draft.endDate) errors.endDate = "End date must be on or after the start date."; return errors; }
export function createInitialProjectState(draft: ProjectDraft, id: string): ProjectState { const project: Project = { id, name: draft.name.trim(), description: draft.description?.trim() || undefined, startDate: draft.startDate, endDate: draft.endDate || undefined, status: draft.status, progress: 0, metadata: { schemaVersion: 2, minimumAppVersion: "1.1.0" } }; return { project, streams: [], tasks: [], milestones: [], people: [], risks: [], decisions: [], relationships: [], dependencies: [], identifierSequences: { ...EMPTY_IDENTIFIER_SEQUENCES } }; }
export function safeProjectFilename(name: string) { const safe = name.normalize("NFKD").replace(/[^a-zA-Z0-9 _-]/g, "").trim().replace(/[ .]+$/g, "").replace(/\s+/g, "-").slice(0, 80) || "project"; return `${safe}.pmp`; }
export function projectReadiness(state: ProjectState) { return [{ label: "Project", ready: Boolean(state.project.name && state.project.startDate) }, { label: "Streams", ready: state.streams.some((x) => !x.deletion.isDeleted) }, { label: "People", ready: state.people.some((x) => !x.deletion.isDeleted) }, { label: "Milestones", ready: state.milestones.some((x) => !x.deletion.isDeleted) }]; }
export function updateProject(patch: Partial<Project>) { return { type: "update-project", apply: (state: ProjectState): ProjectState => ({ ...state, project: { ...state.project, ...patch } }) }; }
