import { describe, expect, it } from "vitest";
import { ProjectRuntime } from "./project-runtime";
import type { ProjectFileService } from "../persistence/project-file-service";
import { DEFAULT_PROJECT_CONFIGURATION } from "../persistence/pmp";

const files = (open: ProjectFileService["open"]): ProjectFileService => ({ open, create: async () => { throw new Error() }, save: async () => { throw new Error() }, saveAs: async () => { throw new Error() }, reload: async () => { throw new Error() }, inspect: async () => { throw new Error() }, acceptExternalModification: async () => { throw new Error() } });
describe("ProjectRuntime", () => {
  it("starts in the launcher and transitions to/cancels creation", () => { const runtime = new ProjectRuntime(files(async () => ({ ok: false, error: { code: "CANCELLED", message: "cancelled" } }))); expect(runtime.getSnapshot().screen).toBe("launcher"); runtime.beginNewProject(); expect(runtime.getSnapshot().screen).toBe("create"); runtime.cancelNewProject(); expect(runtime.getSnapshot().screen).toBe("launcher"); });
  it("keeps cancellation quiet and reports unsupported/invalid files", async () => { const cancelled = new ProjectRuntime(files(async () => ({ ok: false, error: { code: "CANCELLED", message: "cancelled" } }))); await cancelled.openProject(); expect(cancelled.getSnapshot().message).toBeUndefined(); const invalid = new ProjectRuntime(files(async () => ({ ok: false, error: { code: "INVALID_PROJECT", message: "Invalid PMP" } }))); await invalid.openProject(); expect(invalid.getSnapshot().message).toBe("Invalid PMP"); });
  it("returns to launcher on close", () => { const runtime = new ProjectRuntime(files(async () => ({ ok: false, error: { code: "UNSUPPORTED", message: "unsupported" } }))); runtime.beginNewProject(); runtime.closeProject(); expect(runtime.getSnapshot()).toEqual({ screen: "launcher" }); });
});

describe("persistence lifecycle",()=>{it("preserves dirty state and history after a failed save",async()=>{const loaded={handle:{id:"file-1",name:"x.pmp"},state:(await import("../domain/test-fixtures")).makeProjectState(),configuration:DEFAULT_PROJECT_CONFIGURATION,createdAt:"2026-01-01T00:00:00Z",lastSavedAt:"2026-01-01T00:00:00Z"};const service:ProjectFileService={...files(async()=>({ok:true,value:loaded})),create:async()=>({ok:true,value:loaded}),save:async()=>({ok:false,error:{code:"WRITE_FAILED",message:"failed"}}),saveAs:async()=>({ok:true,value:loaded}),reload:async()=>({ok:true,value:loaded}),inspect:async()=>({ok:true,value:{name:"x",size:1,lastModified:1,externallyModified:false}}),acceptExternalModification:async()=>({ok:true,value:{name:"x",size:1,lastModified:1,externallyModified:false}})};const runtime=new ProjectRuntime(service);runtime.activate(loaded);const store=runtime.getSnapshot().active!.store;store.execute({type:"change",apply:state=>({...state,project:{...state.project,progress:50}})});expect((await runtime.saveNow()).ok).toBe(false);expect(store.isDirty()).toBe(true);expect(store.canUndo()).toBe(true);expect(runtime.getSnapshot().saveStatus).toBe("save-failed")})});

describe("autosave scheduling",()=>{it("uses the exact sixty-second interval",async()=>{const {startAutosave}=await import("./project-runtime");let delay=0;let calls=0;let cleared=false;const stop=startAutosave(()=>calls++,((callback:()=>void,ms:number)=>{delay=ms;callback();return 9}) as never,(()=>{cleared=true}) as never);expect(delay).toBe(60_000);expect(calls).toBe(1);stop();expect(cleared).toBe(true)})});

describe("project switching",()=>{it("requires an explicit decision after a dirty-project save failure",async()=>{const loaded={handle:{id:"file-1",name:"x.pmp"},state:(await import("../domain/test-fixtures")).makeProjectState(),configuration:DEFAULT_PROJECT_CONFIGURATION,createdAt:"2026-01-01T00:00:00Z",lastSavedAt:"2026-01-01T00:00:00Z"};let opened=0;const service:ProjectFileService={...files(async()=>{opened++;return{ok:true,value:loaded}}),save:async()=>({ok:false,error:{code:"WRITE_FAILED",message:"failed"}})};const runtime=new ProjectRuntime(service);runtime.activate(loaded);runtime.getSnapshot().active!.store.execute({type:"change",apply:s=>({...s,project:{...s.project,progress:55}})});await runtime.openProject();expect(runtime.getSnapshot().pendingSwitch).toBe(true);expect(opened).toBe(0);runtime.cancelProjectSwitch();expect(runtime.getSnapshot().pendingSwitch).toBe(false);await runtime.continueProjectSwitch();expect(opened).toBe(1)})});
