import{getTaskHierarchyDepth,issueHumanId,setLeafTaskStatus,wouldCreateDependencyCycle,type Dependency,type Task,type TaskScope}from"../../domain";import type{ProjectCommand,ProjectState}from"../../application";
export interface TaskDraft{name:string;scope:TaskScope;parentTaskId?:string;ownerId:string|null;status:Task["status"];progress:number;startDate?:string|null;endDate?:string|null;priority?:Task["priority"];milestoneId?:string}
export function validateTaskDraft(state:ProjectState,draft:TaskDraft,editingId?:string){const errors:string[]=[];if(!draft.name.trim())errors.push("Task name is required.");if(draft.startDate&&draft.endDate&&draft.endDate<draft.startDate)errors.push("End Date must be on or after Start Date.");if(!Number.isInteger(draft.progress)||draft.progress<0||draft.progress>100)errors.push("Progress must be a whole number from 0 to 100.");if(draft.scope.kind==="stream"){const streamId=draft.scope.streamId;if(!state.streams.some(s=>s.id===streamId&&!s.deletion.isDeleted))errors.push("Select an active stream.");}if(draft.ownerId&&!state.people.some(p=>p.id===draft.ownerId&&!p.deletion.isDeleted))errors.push("Select an active owner.");if(draft.parentTaskId){if(draft.parentTaskId===editingId)errors.push("A task cannot be its own parent.");const depth=getTaskHierarchyDepth(draft.parentTaskId,state.tasks);if(depth===null||depth>=4)errors.push("Tasks support a maximum of four hierarchy levels.");let parent=state.tasks.find(t=>t.id===draft.parentTaskId);while(parent?.parentTaskId){if(parent.parentTaskId===editingId)errors.push("Task hierarchy cannot contain a cycle.");parent=state.tasks.find(t=>t.id===parent?.parentTaskId)}}return errors;}
export function createTask(draft:TaskDraft):ProjectCommand{return{type:"create-task",apply(state,ctx){if(validateTaskDraft(state,draft).length)return state;const issued=issueHumanId(state.identifierSequences,"task");const task:Task={...draft,id:ctx.createId(),projectId:state.project.id,humanId:issued.humanId,name:draft.name.trim(),actualCompletionDate:draft.status==="Completed"?ctx.now().slice(0,10):undefined,deletion:{isDeleted:false}};return{...state,tasks:[...state.tasks,task],identifierSequences:issued.sequences}}};}
export function editTask(id:string,patch:Partial<TaskDraft>):ProjectCommand{return{type:"edit-task",apply(state,ctx){const source=state.tasks.find(t=>t.id===id);if(!source)return state;const draft={...source,...patch};if(validateTaskDraft(state,draft,id).length)return state;let next={...source,...patch,name:draft.name.trim()};if(patch.status)next=setLeafTaskStatus(next,patch.status,ctx.now().slice(0,10));return{...state,tasks:state.tasks.map(t=>t.id===id?next:t)}}};}
export function addTaskDependency(predecessorId:string,successorId:string):ProjectCommand{return{type:"add-task-dependency",apply(state,ctx){if(!state.tasks.some(t=>t.id===predecessorId&&!t.deletion.isDeleted)||!state.tasks.some(t=>t.id===successorId&&!t.deletion.isDeleted))return state;const dependency:Dependency={id:ctx.createId(),projectId:state.project.id,predecessor:{kind:"task",id:predecessorId},successor:{kind:"task",id:successorId},type:"Finish-to-Start"};if(wouldCreateDependencyCycle(state.dependencies,dependency))return state;return{...state,dependencies:[...state.dependencies,dependency]}}};}
export function removeTaskDependency(predecessorId:string,successorId:string):ProjectCommand{return{type:"remove-task-dependency",apply(state){return{...state,dependencies:state.dependencies.filter(d=>!(d.predecessor.kind==="task"&&d.successor.kind==="task"&&d.predecessor.id===predecessorId&&d.successor.id===successorId))}}};}
export function canAddTaskDependency(state:ProjectState,predecessorId:string,successorId:string){const candidate:Dependency={id:"candidate",projectId:state.project.id,predecessor:{kind:"task",id:predecessorId},successor:{kind:"task",id:successorId},type:"Finish-to-Start"};return predecessorId!==successorId&&!wouldCreateDependencyCycle(state.dependencies,candidate)}
export function bulkDeleteTasks(ids:readonly string[]):ProjectCommand{return{type:"bulk-delete-tasks",apply(state,ctx){const selected=new Set(ids);if(!ids.length)return state;return{...state,tasks:state.tasks.map(t=>selected.has(t.id)&&!t.deletion.isDeleted?{...t,deletion:{isDeleted:true,deletedAt:ctx.now()}}:t)}}};}
export function isTaskOverdue(task:Task,today:string){return!task.deletion.isDeleted&&Boolean(task.endDate&&task.endDate<today&&task.status!=="Completed"&&task.status!=="Cancelled")}
