import { describe, expect, it } from "vitest";
import { createProjectStore, duplicate, restore, softDelete } from "../../application";
import type { Decision } from "../../domain";
import { makeProjectState, streamFixture } from "../../domain/test-fixtures";
import { createDecision, editDecision, filterDecisions, validateDecision, type DecisionDraft } from "./commands";
const context = { createId: (() => { let id = 0; return () => `id-${++id}`; })(), now: () => "2026-09-15T10:00:00Z" };
const draft: DecisionDraft = { title: "Choose approach", decisionDate: "2026-09-01", ownerId: null, projectWide: true, relatedStreamIds: [], relatedTaskIds: [], relatedMilestoneIds: [], relatedRiskIds: [] };
describe("decision management", () => {
  it("creates, edits, filters and sorts using global history", () => { const store = createProjectStore(makeProjectState(), context); store.execute(createDecision(draft)); const id = store.getState().decisions[0].id; store.execute(editDecision(id, { title: "Choose option A" })); expect(filterDecisions(store.getState(), "option")[0].title).toBe("Choose option A"); expect(store.isDirty()).toBe(true); store.undo(); expect(store.getState().decisions[0].title).toBe(draft.title); store.redo(); });
  it("validates active relationships", () => { expect(validateDecision(makeProjectState(), { ...draft, relatedStreamIds: ["missing"] })).toContain("Relationships must target active entities."); expect(validateDecision(makeProjectState({ streams: [streamFixture()] }), { ...draft, relatedStreamIds: ["stream-1"] })).toHaveLength(0); });
  it("duplicates with fresh sequential identity, current injected date, active relationships and no inactive owner", () => { const decision: Decision = { ...draft, id: "d", projectId: "project-1", humanId: "DECISION-001", ownerId: "p", relatedStreamIds: ["stream-1"] , deletion: { isDeleted: false } }; const store = createProjectStore(makeProjectState({ streams: [streamFixture()], people: [{ id: "p", projectId: "project-1", humanId: "PERSON-001", name: "Former", deletion: { isDeleted: true } }], decisions: [decision] }), context); store.execute(duplicate("decision", "d")); expect(store.getState().decisions[1]).toMatchObject({ humanId: "DECISION-002", decisionDate: "2026-09-15", ownerId: null, relatedStreamIds: ["stream-1"] }); expect(store.getState().decisions[1].id).not.toBe("d"); });
  it("soft deletes, includes deleted on demand, and restores", () => { const store = createProjectStore(makeProjectState(), context); store.execute(createDecision(draft)); const id = store.getState().decisions[0].id; store.execute(softDelete("decision", id)); expect(filterDecisions(store.getState(), "")).toHaveLength(0); expect(filterDecisions(store.getState(), "", true)).toHaveLength(1); store.execute(restore("decision", id)); expect(filterDecisions(store.getState(), "")).toHaveLength(1); });
});
