"use client";
import { useState } from "react";
import type { ProjectStore } from "../../application";
import { duplicate, restore, softDelete } from "../../application";
import { EmptyState } from "../shell/shell";
import { createDecision, editDecision, filterDecisions } from "./commands";
export function DecisionLog({ store }: { store: ProjectStore }) {
  const [showDeleted, setShowDeleted] = useState(false); const [query, setQuery] = useState(""); const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const state = store.getState(); const decisions = filterDecisions(state, query, showDeleted);
  return <section className="panel"><div className="title-row"><div><p className="eyebrow">Governance record</p><h1>Decision Log</h1></div><label className="toggle"><input type="checkbox" checked={showDeleted} onChange={(event) => setShowDeleted(event.target.checked)} /> Show Deleted</label></div><div className="inline-form"><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Decision date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><button onClick={() => { if (store.execute(createDecision({ title, decisionDate: date, ownerId: null, projectWide: true, relatedStreamIds: [], relatedTaskIds: [], relatedMilestoneIds: [], relatedRiskIds: [] }))) { setTitle(""); setDate(""); } }}>Add Decision</button><label>Filter<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ID or title" /></label></div>{decisions.length === 0 ? <EmptyState title="No matching decisions" description="Record a decision or change the current filter." /> : <table><thead><tr><th>ID / title</th><th>Date</th><th>Owner</th><th>Context</th><th>Relationships</th><th>Actions</th></tr></thead><tbody>{decisions.map((decision) => <tr key={decision.id}><td><small>{decision.humanId}</small><input disabled={decision.deletion.isDeleted} value={decision.title} onChange={(event) => store.execute(editDecision(decision.id, { title: event.target.value }))} /></td><td><input type="date" disabled={decision.deletion.isDeleted} value={decision.decisionDate} onChange={(event) => store.execute(editDecision(decision.id, { decisionDate: event.target.value }))} /></td><td><select disabled={decision.deletion.isDeleted} value={decision.ownerId ?? ""} onChange={(event) => store.execute(editDecision(decision.id, { ownerId: event.target.value || null }))}><option value="">Unassigned</option>{state.people.filter((person) => !person.deletion.isDeleted).map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></td><td>{decision.projectWide ? "Project-wide" : "Related entities"}</td><td>{decision.relatedStreamIds.length + decision.relatedTaskIds.length + decision.relatedMilestoneIds.length + decision.relatedRiskIds.length}</td><td>{decision.deletion.isDeleted ? <button onClick={() => store.execute(restore("decision", decision.id))}>Restore</button> : <><button className="secondary" onClick={() => store.execute(duplicate("decision", decision.id))}>Duplicate</button><button className="danger" onClick={() => store.execute(softDelete("decision", decision.id))}>Delete</button></>}</td></tr>)}</tbody></table>}</section>;
}
