import { describe, expect, it } from "vitest";
import { createProjectStore, duplicate, restore, softDelete } from "../../application";
import { makeProjectState, streamFixture, taskFixture } from "../../domain/test-fixtures";
import { createMilestone, editMilestone, selectUpcomingMilestones, validateMilestone, type MilestoneDraft } from "./commands";

const context = { createId: (() => { let id = 0; return () => `id-${++id}`; })(), now: () => "2026-09-15T12:00:00Z" };
const draft: MilestoneDraft = { name: "Gate", plannedDate: "2026-10-01", status: "Planned", ownerId: null, scope: { kind: "project" }, relatedTaskIds: [] };
describe("milestone management", () => {
  it("validates, creates, edits, completes and reopens through history", () => { const store = createProjectStore(makeProjectState(), context); expect(validateMilestone(store.getState(), { ...draft, plannedDate: "" })).toContain("Milestone date is required."); store.execute(createMilestone(draft)); const id = store.getState().milestones[0].id; store.execute(editMilestone(id, { name: "Launch", status: "Complete" })); expect(store.getState().milestones[0]).toMatchObject({ name: "Launch", actualCompletionDate: "2026-09-15" }); store.execute(editMilestone(id, { status: "Planned" })); expect(store.getState().milestones[0].actualCompletionDate).toBeUndefined(); expect(store.isDirty()).toBe(true); store.undo(); store.redo(); });
  it("associates active tasks and supports delete/restore", () => { const store = createProjectStore(makeProjectState({ tasks: [taskFixture()] }), context); store.execute(createMilestone({ ...draft, relatedTaskIds: ["task-1"] })); const milestone = store.getState().milestones[0]; expect(milestone.relatedTaskIds).toEqual(["task-1"]); store.execute(softDelete("milestone", milestone.id)); expect(selectUpcomingMilestones(store.getState())).toHaveLength(0); store.execute(restore("milestone", milestone.id)); expect(selectUpcomingMilestones(store.getState())).toHaveLength(1); });
  it("duplicates with fresh sequential identity and resets completion and inactive owner", () => { const state = makeProjectState({ people: [{ id: "person", projectId: "project-1", humanId: "PERSON-001", name: "Former", deletion: { isDeleted: true } }], milestones: [{ id: "m1", projectId: "project-1", humanId: "MILESTONE-001", name: "Done", plannedDate: "2026-10-01", status: "Complete", ownerId: "person", scope: { kind: "project" }, relatedTaskIds: [], actualCompletionDate: "2026-09-01", deletion: { isDeleted: false } }] }); const store = createProjectStore(state, context); store.execute(duplicate("milestone", "m1")); expect(store.getState().milestones[1]).toMatchObject({ humanId: "MILESTONE-002", status: "Tentative", ownerId: null }); expect(store.getState().milestones[1].id).not.toBe("m1"); expect(store.getState().milestones[1].actualCompletionDate).toBeUndefined(); });
});

it("preserves hidden deleted Stream references while editing active scope selections",()=>{const active=streamFixture(),deleted=streamFixture({id:"deleted-stream",humanId:"STREAM-002",deletion:{isDeleted:true}}),milestone={id:"m",projectId:"project-1",humanId:"MILESTONE-001"as const,name:"Gate",plannedDate:"2026-10-01",status:"Planned"as const,ownerId:null,scope:{kind:"streams"as const,streamIds:[deleted.id]},relatedTaskIds:[],deletion:{isDeleted:false}};const store=createProjectStore(makeProjectState({streams:[active,deleted],milestones:[milestone]}),context);store.execute(editMilestone("m",{scope:{kind:"streams",streamIds:[deleted.id,active.id]}}));expect(store.getState().milestones[0].scope).toEqual({kind:"streams",streamIds:[deleted.id,active.id]})});
