import { describe, expect, it } from "vitest";
import { makeProjectState, streamFixture, taskFixture } from "../../domain/test-fixtures";
import { barPosition, buildGanttModel, positionForDate } from "./model";

describe("Gantt model", () => {
  it("builds a deterministic empty model", () => { const state = makeProjectState(); expect(buildGanttModel(state)).toEqual(buildGanttModel(state)); expect(buildGanttModel(state).rows).toHaveLength(0); });
  it("creates stream, flat, nested and milestone rows while excluding deleted items", () => { const tasks = [taskFixture({ id: "l1", startDate: "2026-02-01", endDate: "2026-02-02" }), taskFixture({ id: "l2", parentTaskId: "l1" }), taskFixture({ id: "l3", parentTaskId: "l2" }), taskFixture({ id: "l4", parentTaskId: "l3" }), taskFixture({ id: "gone", deletion: { isDeleted: true } })]; const state = makeProjectState({ streams: [streamFixture()], tasks, milestones: [{ id: "m", projectId: "project-1", humanId: "MILESTONE-001", name: "Gate", plannedDate: "2026-03-01", status: "Planned", ownerId: null, scope: { kind: "project" }, relatedTaskIds: [], deletion: { isDeleted: false } }] }); const model = buildGanttModel(state); expect(model.rows.map((row) => row.kind)).toEqual(["stream", "task", "task", "task", "task", "milestone"]); expect(model.rows.find((row) => row.id === "l4")).toMatchObject({ depth: 4 }); expect(model.rows.some((row) => row.id === "gone")).toBe(false); });
  it("positions dates and progress deterministically and responds to project dates", () => { expect(positionForDate("2026-01-06", "2026-01-01", "2026-01-11")).toBe(50); expect(barPosition("2026-01-01", "2026-01-06", "2026-01-01", "2026-01-11")).toEqual({ left: 0, width: 50 }); const first = buildGanttModel(makeProjectState()).start; const second = buildGanttModel(makeProjectState({ project: { ...makeProjectState().project, startDate: "2025-01-01" } })).start; expect(second).not.toBe(first); });
  it("filters dependencies with inactive endpoints", () => { const state = makeProjectState({ tasks: [taskFixture({ id: "active" }), taskFixture({ id: "deleted", deletion: { isDeleted: true } })], dependencies: [{ id: "d", projectId: "project-1", predecessor: { kind: "task", id: "active" }, successor: { kind: "task", id: "deleted" }, type: "Finish-to-Start" }] }); expect(buildGanttModel(state).dependencies).toHaveLength(0); });
});
