"use client";
import { useState } from "react";
import type { ProjectStore } from "../../application";
import { buildTubeMap } from "./model";
const dateLabel = (date: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "long", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)).replace(" ", "/");
export function TubeMapView({ store }: { store: ProjectStore }) {
  const [labels, setLabels] = useState<"week" | "date">("week");
  const [windowOffset, setWindowOffset] = useState(0);
  const anchor = new Date();
  anchor.setUTCDate(anchor.getUTCDate() + windowOffset * 84);
  const model = buildTubeMap(store.getState(), anchor.toISOString().slice(0, 10));
  return <section className="panel"><div className="title-row"><div><p className="eyebrow">12-week governance roadmap</p><h1>Tube Map</h1></div><label>Axis <select value={labels} onChange={(event) => setLabels(event.target.value as typeof labels)}><option value="week">Week Number</option><option value="date">Monday date</option></select></label></div><div className="tube-map"><div className="tube-axis"><b>Stream</b>{model.weeks.map((week) => <span key={week.date}>{labels === "week" ? week.label : dateLabel(week.date)}</span>)}</div><div className="tube-body" style={{ height: `${model.height}px` }}>{model.streams.map((stream) => <div className="tube-line" key={stream.id} style={{ top: `${stream.top}px`, height: `${stream.height}px` }}><strong>{stream.label}</strong><div /></div>)}<svg className="tube-connections" viewBox={`0 0 100 ${model.height}`} preserveAspectRatio="none" aria-label={`${model.connections.length} milestone connections`}>{model.connections.map((connection) => <path key={`${connection.from}:${connection.to}`} d={`M ${connection.fromX} ${connection.fromY} C ${(connection.fromX + connection.toX) / 2} ${connection.fromY}, ${(connection.fromX + connection.toX) / 2} ${connection.toY}, ${connection.toX} ${connection.toY}`} />)}</svg>{model.stations.filter((station) => station.boundary === "inside").map((station) => <div className="tube-station" key={station.id} style={{ left: `${station.x}%`, top: `${station.y}px` }}><i /><small>{station.label}</small></div>)}</div><footer className="tube-navigation"><button type="button" className="secondary" onClick={() => setWindowOffset(value => value - 1)} aria-label="Previous 12 weeks">← Previous 12 weeks ({model.stations.filter(station => station.boundary === "before").length} before)</button><span aria-live="polite">{model.start} – {model.end} · {model.connections.length} connections</span><button type="button" className="secondary" onClick={() => setWindowOffset(value => value + 1)} aria-label="Next 12 weeks">Next 12 weeks ({model.stations.filter(station => station.boundary === "after").length} after) →</button><button type="button" className="secondary" disabled={windowOffset === 0} onClick={() => setWindowOffset(0)}>Current 12 weeks</button></footer></div></section>;
}
