"use client";
import { useState, useSyncExternalStore } from "react";
import { BrowserProjectFileService } from "@/persistence/project-file-service/browser";
import { createBrowserFileAccess } from "@/runtime/browser-access";
import { ProjectRuntime } from "@/runtime/project-runtime";
import { AppShell } from "@/features/shell/shell";
import { Overview } from "@/features/overview/overview";
import { createInitialProjectState, safeProjectFilename, validateProjectDraft, type ProjectDraft } from "@/features/overview/project";
import { PeopleModule, StreamsModule } from "@/features/resources/resources";
import { TasksModule } from "@/features/tasks/tasks";
import { MilestonesModule } from "@/features/milestones/milestones";
import { GanttView } from "@/features/gantt/gantt";
import { TubeMapView } from "@/features/tube-map/tube-map";
import { RiskLog } from "@/features/risks/risks";
import { DecisionLog } from "@/features/decisions/decisions";

const runtime = new ProjectRuntime(new BrowserProjectFileService(createBrowserFileAccess()));
export function ProjectManager() {
  const state = useSyncExternalStore(runtime.subscribe, runtime.getSnapshot, runtime.getSnapshot);
  if (state.screen === "workspace") return <AppShell store={state.active?.store} onClose={() => runtime.closeProject()} onSave={async () => { const active = runtime.getSnapshot().active; if (!active) return; const result = await runtime.fileService.save(active.handle, active.store.getState(), { runtimeVersion: "0.1.0", createdAt: active.loaded.createdAt, configuration: active.loaded.configuration }); if (!result.ok) throw new Error(result.error.message); active.store.acknowledgeSave(); }}>{(module,navigate) => state.active && module === "Overview" ? <Overview store={state.active.store} navigate={navigate}/> : state.active && module === "Streams" ? <StreamsModule store={state.active.store}/> : state.active && module === "People" ? <PeopleModule store={state.active.store}/> : state.active && module === "Tasks" ? <TasksModule store={state.active.store}/> : state.active && module === "Milestones" ? <MilestonesModule store={state.active.store}/> : state.active && module === "Gantt" ? <GanttView store={state.active.store}/> : state.active && module === "Tube Map" ? <TubeMapView store={state.active.store}/> : state.active && module === "Risk Log" ? <RiskLog store={state.active.store}/> : state.active && module === "Decision Log" ? <DecisionLog store={state.active.store}/> : <section className="panel"><p className="eyebrow">Module</p><h1>{module}</h1><p className="empty">This module is ready for its implementation block.</p></section>}</AppShell>;
  if (state.screen === "create") return <NewProject />;
  return <main className="launcher"><section><p className="eyebrow">Local project workspace</p><h1>Project Manager</h1><p className="muted">Create or open a portable project file. Your project stays on this computer.</p>{state.message && <div role="alert" className="alert">{state.message}</div>}<div className="actions"><button onClick={() => runtime.beginNewProject()}>New Project</button><button className="secondary" onClick={() => void runtime.openProject()}>Open Project</button></div></section></main>;
}
function NewProject(){ const [draft,setDraft]=useState<ProjectDraft>({name:"",description:"",startDate:"",endDate:"",status:"Not Started"}); const [errors,setErrors]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const create=async()=>{const validation=validateProjectDraft(draft);setErrors(validation);if(Object.keys(validation).length)return;const result=await runtime.createProject(createInitialProjectState(draft,crypto.randomUUID()),safeProjectFilename(draft.name));if(!result.ok&&result.error.code!=="CANCELLED")setMessage(result.error.message);};return <main className="launcher"><section><p className="eyebrow">Project factory</p><h1>New Project</h1>{message&&<div role="alert" className="alert">{message}</div>}<div className="form-grid"><label>Project name<input autoFocus value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/>{errors.name&&<small>{errors.name}</small>}</label><label>Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Start date<input type="date" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/>{errors.startDate&&<small>{errors.startDate}</small>}</label><label>End date<input type="date" value={draft.endDate} onChange={e=>setDraft({...draft,endDate:e.target.value})}/>{errors.endDate&&<small>{errors.endDate}</small>}</label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as ProjectDraft["status"]})}>{["Not Started","In Progress","On Hold","Completed","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="actions"><button onClick={()=>void create()}>Choose File & Create</button><button className="secondary" onClick={()=>runtime.cancelNewProject()}>Cancel</button></div></section></main>}
