import type { ProjectState } from "@/application";
import type { ModuleName } from "@/features/shell/shell";
export type WarningEntityType = "Stream" | "Task" | "Milestone";
export type WarningType = "Invalid date range" | "Outside project dates" | "Outside stream dates";
export interface ProjectWarning { readonly id:string; readonly type:WarningType; readonly severity:"warning"; readonly entityType:WarningEntityType; readonly entityId:string; readonly humanId:string; readonly entityName:string; readonly description:string; readonly relatedDate?:string; readonly destination:ModuleName }
const before=(date?:string,boundary?:string)=>Boolean(date&&boundary&&date<boundary); const after=(date?:string,boundary?:string)=>Boolean(date&&boundary&&date>boundary);
export function deriveProjectWarnings(state:ProjectState):ProjectWarning[]{const warnings:ProjectWarning[]=[];const add=(warning:Omit<ProjectWarning,"severity">)=>warnings.push({...warning,severity:"warning"});
for(const stream of state.streams.filter(x=>!x.deletion.isDeleted)){if(stream.startDate&&stream.endDate&&stream.startDate>stream.endDate)add({id:`stream-range:${stream.id}`,type:"Invalid date range",entityType:"Stream",entityId:stream.id,humanId:stream.humanId,entityName:stream.name,description:"Stream starts after it ends.",relatedDate:stream.startDate,destination:"Streams"});if(before(stream.startDate,state.project.startDate)||after(stream.endDate,state.project.endDate))add({id:`stream-project:${stream.id}`,type:"Outside project dates",entityType:"Stream",entityId:stream.id,humanId:stream.humanId,entityName:stream.name,description:"Stream dates extend outside the project date range.",relatedDate:before(stream.startDate,state.project.startDate)?stream.startDate:stream.endDate,destination:"Streams"});)}
const streams=new Map(state.streams.filter(x=>!x.deletion.isDeleted).map(x=>[x.id,x]));for(const task of state.tasks.filter(x=>!x.deletion.isDeleted)){if(task.startDate&&task.endDate&&task.startDate>task.endDate)add({id:`task-range:${task.id}`,type:"Invalid date range",entityType:"Task",entityId:task.id,humanId:task.humanId,entityName:task.name,description:"Task starts after it ends.",relatedDate:task.startDate,destination:"Tasks"});if(before(task.startDate,state.project.startDate)||after(task.endDate,state.project.endDate))add({id:`task-project:${task.id}`,type:"Outside project dates",entityType:"Task",entityId:task.id,humanId:task.humanId,entityName:task.name,description:"Task dates extend outside the project date range.",relatedDate:before(task.startDate,state.project.startDate)?task.startDate:task.endDate,destination:"Tasks"});if(task.scope.kind==="stream"){const stream=streams.get(task.scope.streamId);if(stream&&(before(task.startDate,stream.startDate)||after(task.endDate,stream.endDate)))add({id:`task-stream:${task.id}`,type:"Outside stream dates",entityType:"Task",entityId:task.id,humanId:task.humanId,entityName:task.name,description:`Task dates extend outside ${stream.name}.`,relatedDate:before(task.startDate,stream.startDate)?task.startDate:task.endDate,destination:"Tasks"});}}
for(const milestone of state.milestones.filter(x=>!x.deletion.isDeleted)){if(before(milestone.plannedDate,state.project.startDate)||after(milestone.plannedDate,state.project.endDate))add({id:`milestone-project:${milestone.id}`,type:"Outside project dates",entityType:"Milestone",entityId:milestone.id,humanId:milestone.humanId,entityName:milestone.name,description:"Milestone is outside the project date range.",relatedDate:milestone.plannedDate,destination:"Milestones"});if(milestone.scope.kind==="streams"&&milestone.scope.streamIds.length){const related=milestone.scope.streamIds.map(id=>streams.get(id)).filter((x):x is NonNullable<typeof x>=>Boolean(x));if(related.length&&related.every(stream=>before(milestone.plannedDate,stream.startDate)||after(milestone.plannedDate,stream.endDate)))add({id:`milestone-stream:${milestone.id}`,type:"Outside stream dates",entityType:"Milestone",entityId:milestone.id,humanId:milestone.humanId,entityName:milestone.name,description:"Milestone is outside all related stream date ranges.",relatedDate:milestone.plannedDate,destination:"Milestones"});}}
return warnings.sort((a,b)=>(a.relatedDate??"9999-99-99").localeCompare(b.relatedDate??"9999-99-99")||a.entityType.localeCompare(b.entityType)||a.humanId.localeCompare(b.humanId)||a.type.localeCompare(b.type));}
