import { describe, expect, it } from "vitest";
import { createProjectStore, duplicate, restore, softDelete } from "../../application";
import { calculateRiskLevel, DEFAULT_RISK_MATRIX, type Risk } from "../../domain";
import { makeProjectState } from "../../domain/test-fixtures";
import { addRiskAction, createRisk, editRisk, editRiskAction, isRiskActionOverdue, selectOpenRisks, validateRisk, type RiskDraft } from "./commands";
const context = { createId: (() => { let id = 0; return () => `id-${++id}`; })(), now: () => "2026-09-15T00:00:00Z" };
const draft: RiskDraft = { title: "Schedule", status: "Open", probability: "Medium", impact: "High", ownerId: null, projectWide: true, relatedStreamIds: [], relatedTaskIds: [], relatedMilestoneIds: [] };
describe("risk management", () => {
  it("creates, edits and uses configured matrix calculation", () => { const store = createProjectStore(makeProjectState(), context); store.execute(createRisk(draft)); expect(store.getState().risks[0].riskLevel).toBe(calculateRiskLevel("Medium", "High", DEFAULT_RISK_MATRIX)); store.execute(editRisk(store.getState().risks[0].id, { probability: "Low" })); expect(store.getState().risks[0].riskLevel).toBe("Medium"); expect(store.isDirty()).toBe(true); });
  it("validates owners and relationships", () => { expect(validateRisk(makeProjectState(), { ...draft, ownerId: "missing" })).toContain("Owner must be active."); expect(validateRisk(makeProjectState(), { ...draft, relatedTaskIds: ["missing"] })).toContain("Relationships must target active entities."); });
  it("creates, edits, closes and reopens actions with overdue derivation", () => { const store = createProjectStore(makeProjectState(), context); store.execute(createRisk(draft)); const id = store.getState().risks[0].id; store.execute(addRiskAction(id, "Mitigate", "2026-01-01")); const action = store.getState().risks[0].actions[0]; expect(isRiskActionOverdue(action, "2026-09-15")).toBe(true); store.execute(editRiskAction(id, action.id, { description: "Mitigate now", status: "Complete" })); expect(store.getState().risks[0].actions[0].status).toBe("Complete"); store.execute(editRiskAction(id, action.id, { status: "Open" })); expect(store.getState().risks[0].actions[0].status).toBe("Open"); });
  it("duplicates fresh identities, reopens actions, clears deleted owners and supports lifecycle history", () => { const risk: Risk = { ...draft, id: "r", projectId: "project-1", humanId: "RISK-001", riskLevel: "High", ownerId: "p", actions: [{ id: "a", description: "Action", status: "Complete" }], deletion: { isDeleted: false } }; const store = createProjectStore(makeProjectState({ people: [{ id: "p", projectId: "project-1", humanId: "PERSON-001", name: "Former", deletion: { isDeleted: true } }], risks: [risk] }), context); store.execute(duplicate("risk", "r")); const copy = store.getState().risks[1]; expect(copy).toMatchObject({ humanId: "RISK-002", status: "Open", ownerId: null }); expect(copy.id).not.toBe("r"); expect(copy.actions[0]).toMatchObject({ status: "Open" }); expect(copy.actions[0].id).not.toBe("a"); store.execute(softDelete("risk", "r")); expect(selectOpenRisks(store.getState())).toHaveLength(1); store.execute(restore("risk", "r")); store.undo(); store.redo(); });
});
