import { calculateRiskLevel, issueHumanId, type Risk, type RiskAction, type RiskRating, type RiskStatus } from "../../domain";
import type { ProjectCommand, ProjectState } from "../../application";
export interface RiskDraft { title: string; description?: string; status: RiskStatus; probability: RiskRating; impact: RiskRating; ownerId: string | null; dueDate?: string; projectWide: boolean; relatedStreamIds: readonly string[]; relatedTaskIds: readonly string[]; relatedMilestoneIds: readonly string[] }
const active = (items: readonly { id: string; deletion: { isDeleted: boolean } }[], id: string) => items.some((item) => item.id === id && !item.deletion.isDeleted);
export function validateRisk(state: ProjectState, draft: RiskDraft) { const errors: string[] = []; if (!draft.title.trim()) errors.push("Risk title is required."); if (draft.ownerId && !active(state.people, draft.ownerId)) errors.push("Owner must be active."); if (draft.relatedStreamIds.some((id) => !active(state.streams, id)) || draft.relatedTaskIds.some((id) => !active(state.tasks, id)) || draft.relatedMilestoneIds.some((id) => !active(state.milestones, id))) errors.push("Relationships must target active entities."); return errors; }
export function createRisk(draft: RiskDraft): ProjectCommand { return { type: "create-risk", apply(state, context) { if (validateRisk(state, draft).length) return state; const issued = issueHumanId(state.identifierSequences, "risk"); const risk: Risk = { ...draft, title: draft.title.trim(), id: context.createId(), projectId: state.project.id, humanId: issued.humanId, riskLevel: calculateRiskLevel(draft.probability, draft.impact), actions: [], deletion: { isDeleted: false } }; return { ...state, risks: [...state.risks, risk], identifierSequences: issued.sequences }; } }; }
export function editRisk(id: string, patch: Partial<RiskDraft>): ProjectCommand { return { type: "edit-risk", apply(state) { const current = state.risks.find((risk) => risk.id === id); if (!current) return state; const draft = { ...current, ...patch }; if (validateRisk(state, draft).length) return state; return { ...state, risks: state.risks.map((risk) => risk.id === id ? { ...risk, ...patch, title: draft.title.trim(), riskLevel: calculateRiskLevel(draft.probability, draft.impact) } : risk) }; } }; }
export function addRiskAction(riskId: string, description: string, dueDate?: string): ProjectCommand { return { type: "add-risk-action", apply(state, context) { if (!description.trim()) return state; const action: RiskAction = { id: context.createId(), description: description.trim(), status: "Open", dueDate: dueDate || undefined }; return { ...state, risks: state.risks.map((risk) => risk.id === riskId ? { ...risk, actions: [...risk.actions, action] } : risk) }; } }; }
export function editRiskAction(riskId: string, actionId: string, patch: Partial<Omit<RiskAction, "id">>): ProjectCommand { return { type: "edit-risk-action", apply(state) { if (patch.description !== undefined && !patch.description.trim()) return state; return { ...state, risks: state.risks.map((risk) => risk.id === riskId ? { ...risk, actions: risk.actions.map((action) => action.id === actionId ? { ...action, ...patch, description: patch.description?.trim() ?? action.description } : action) } : risk) }; } }; }
export const isRiskActionOverdue = (action: RiskAction, today: string) => action.status === "Open" && Boolean(action.dueDate && action.dueDate < today);
export const selectOpenRisks = (state: ProjectState) => state.risks.filter((risk) => !risk.deletion.isDeleted && risk.status !== "Closed");
