import { describe, expect, it } from "vitest";
import { makeProjectState } from "../../domain/test-fixtures";
import { canonicalJson } from "./canonical";
import { deserializeProject, serializeProject } from "./codec";
import { inspectProjectCompatibility } from "./validation";
import { CURRENT_PMP_FORMAT_VERSION, CURRENT_PROJECT_SCHEMA_VERSION, PMP_FORMAT_IDENTIFIER } from "./types";

const meta = { createdAt: "2026-09-15T09:00:00.000Z", lastSavedAt: "2026-09-15T09:01:00.000Z", runtimeVersion: "0.1.0" };

describe("PMP v1", () => {
  it("canonicalises object keys", () => expect(canonicalJson({ z: 1, a: { y: 2, b: 3 } })).toBe('{"a":{"b":3,"y":2},"z":1}'));
  it("reports current compatibility", () => expect(inspectProjectCompatibility({ formatIdentifier: PMP_FORMAT_IDENTIFIER, formatVersion: CURRENT_PMP_FORMAT_VERSION, schemaVersion: CURRENT_PROJECT_SCHEMA_VERSION })).toMatchObject({ compatible: true, requiresMigration: false }));
  it("rejects future format", () => expect(inspectProjectCompatibility({ formatIdentifier: PMP_FORMAT_IDENTIFIER, formatVersion: 2, schemaVersion: 1 }).format).toBe("UNSUPPORTED_NEWER"));
  it("rejects empty input", () => expect(deserializeProject(new Uint8Array()).ok).toBe(false));
  it("round trips representative project state", () => { const state = makeProjectState(); const encoded = serializeProject(state, meta); expect(encoded.ok).toBe(true); if (!encoded.ok) return; const decoded = deserializeProject(encoded.value); expect(decoded.ok).toBe(true); if (decoded.ok) expect(decoded.value.projectState.project.id).toBe(state.project.id); });
  it("serializes deterministically", () => { const state = makeProjectState(); const a = serializeProject(state, meta); const b = serializeProject(state, meta); expect(a.ok && b.ok && Array.from(a.value).join(",") === Array.from(b.value).join(",")).toBe(true); });
});

describe("adversarial project validation",()=>{it("rejects malformed UTF-8 and non-ZIP data",()=>{expect(deserializeProject(Uint8Array.from([0x50,0x4d,0xff])).ok).toBe(false)});it("rejects invalid and duplicate human-readable IDs before serialization",()=>{const state=makeProjectState({streams:[{id:"s1",projectId:"project-1",humanId:"STREAM-X",name:"unsafe",ownerId:null,status:"Not Started",deletion:{isDeleted:false}}]});expect(serializeProject(state,meta).ok).toBe(false)});it("rejects invalid dependency references",()=>{const state=makeProjectState({dependencies:[{id:"d1",projectId:"project-1",type:"Finish-to-Start",predecessor:{kind:"task",id:"missing"},successor:{kind:"milestone",id:"missing"}}]});expect(serializeProject(state,meta).ok).toBe(false)})});

describe("hardened PMP boundaries",()=>{const encode=(state=makeProjectState())=>{const result=serializeProject(state,meta);expect(result.ok).toBe(true);return result.ok?result.value:new Uint8Array()};it("rejects an archive entry renamed to a traversal path",()=>{const bytes=encode().slice();const original=new TextEncoder().encode("manifest.json"),unsafe=new TextEncoder().encode("../nifest.json");const at=bytes.findIndex((_,i)=>original.every((b,j)=>bytes[i+j]===b));bytes.set(unsafe,at);expect(deserializeProject(bytes).ok).toBe(false)});it("rejects an unexpected equal-length archive entry",()=>{const bytes=encode().slice(),original=new TextEncoder().encode("project.json"),unsafe=new TextEncoder().encode("project.exe");const at=bytes.findIndex((_,i)=>original.every((b,j)=>bytes[i+j]===b));bytes.set(unsafe,at);expect(deserializeProject(bytes).ok).toBe(false)});it("rejects impossible calendar dates",()=>expect(serializeProject(makeProjectState({project:{...makeProjectState().project,startDate:"2026-02-30"}}),meta).ok).toBe(false));it("rejects corrupt identifier sequences",()=>{expect(serializeProject(makeProjectState({identifierSequences:{stream:-1,task:0,milestone:0,person:0,risk:0,decision:0}}),meta).ok).toBe(false)});it("rejects cyclic dependencies",()=>{const task=(id:string,humanId:`TASK-${string}`)=>({id,projectId:"project-1",humanId,name:id,scope:{kind:"project" as const},status:"Not Started" as const,ownerId:null,progress:0,deletion:{isDeleted:false}});const state=makeProjectState({tasks:[task("a","TASK-001"),task("b","TASK-002")],identifierSequences:{stream:0,task:2,milestone:0,person:0,risk:0,decision:0},dependencies:[{id:"d1",projectId:"project-1",type:"Finish-to-Start",predecessor:{kind:"task",id:"a"},successor:{kind:"task",id:"b"}},{id:"d2",projectId:"project-1",type:"Finish-to-Start",predecessor:{kind:"task",id:"b"},successor:{kind:"task",id:"a"}}]});expect(serializeProject(state,meta).ok).toBe(false)});it("rejects oversized container input without processing it",()=>expect(deserializeProject(new Uint8Array(32*1024*1024+1)).ok).toBe(false))});
