import { DEPENDENCY_TYPES, LIFECYCLE_STATUSES, MILESTONE_STATUSES, PRIORITIES, RISK_ACTION_STATUSES, RISK_RATINGS, RISK_STATUSES, calculateRiskLevel} from "../../domain";
import type { ProjectState } from "../../application";
const object=(value:unknown):value is Record<string,unknown>=>value!==null&&typeof value==="object"&&!Array.isArray(value);
const text=(value:unknown,required=false):value is string=>typeof value==="string"&&value.length<=100_000&&(!required||value.trim().length>0);
const id=(value:unknown):value is string=>text(value,true)&&value.length<=200;
const date=(value:unknown,optional=true)=>{if(value===undefined)return optional;if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const [year,month,day]=value.split("-").map(Number),parsed=new Date(Date.UTC(year,month-1,day));return parsed.getUTCFullYear()===year&&parsed.getUTCMonth()===month-1&&parsed.getUTCDate()===day;};
const deletion=(value:unknown)=>object(value)&&typeof value.isDeleted==="boolean"&&(!value.isDeleted||typeof value.deletedAt==="string")&&Object.keys(value).every(key=>["isDeleted","deletedAt"].includes(key));
const identity=(value:unknown,prefix:string,projectId:string)=>object(value)&&id(value.id)&&value.projectId===projectId&&typeof value.humanId==="string"&&new RegExp(`^${prefix}-[0-9]{3,}$`).test(value.humanId)&&deletion(value.deletion);
const ids=(value:unknown)=>Array.isArray(value)&&value.every(id);
export function validatePersistedState(state:ProjectState):string|undefined{
 const p=state.project;if(!object(p)||!id(p.id)||!text(p.name,true)||!date(p.startDate,false)||!date(p.endDate)||!LIFECYCLE_STATUSES.includes(p.status)||!Number.isInteger(p.progress)||p.progress<0||p.progress>100||!object(p.metadata)||!Number.isInteger(p.metadata.schemaVersion)||!text(p.metadata.minimumAppVersion,true))return"Project structure is invalid.";
 const ownerIds=new Set(state.people.map(x=>x.id));const owner=(value:unknown)=>value===null||id(value)&&ownerIds.has(value);
 if(state.people.some(x=>!identity(x,"PERSON",p.id)||!text(x.name,true)))return"Person structure is invalid.";
 if(state.streams.some(x=>!identity(x,"STREAM",p.id)||!text(x.name,true)||!text(x.description??"")||!owner(x.ownerId)||!LIFECYCLE_STATUSES.includes(x.status)||!date(x.startDate)||!date(x.endDate)||(x.priority!==undefined&&!PRIORITIES.includes(x.priority))))return"Stream structure is invalid.";
 const streamIds=new Set(state.streams.map(x=>x.id)),taskIds=new Set(state.tasks.map(x=>x.id)),milestoneIds=new Set(state.milestones.map(x=>x.id)),riskIds=new Set(state.risks.map(x=>x.id));
 if(state.tasks.some(x=>!identity(x,"TASK",p.id)||!text(x.name,true)||!text(x.description??"")||!owner(x.ownerId)||!LIFECYCLE_STATUSES.includes(x.status)||!date(x.startDate)||!date(x.endDate)||!date(x.actualCompletionDate)||!Number.isInteger(x.progress)||x.progress<0||x.progress>100||(x.priority!==undefined&&!PRIORITIES.includes(x.priority))||!object(x.scope)||(x.scope.kind==="stream"?!id(x.scope.streamId)||!streamIds.has(x.scope.streamId):x.scope.kind!=="project")||(x.parentTaskId!==undefined&&!taskIds.has(x.parentTaskId))||(x.milestoneId!==undefined&&!milestoneIds.has(x.milestoneId))))return"Task structure is invalid.";
 if(state.milestones.some(x=>!identity(x,"MILESTONE",p.id)||!text(x.name,true)||!text(x.description??"")||!owner(x.ownerId)||!date(x.plannedDate,false)||!date(x.actualCompletionDate)||!MILESTONE_STATUSES.includes(x.status)||(x.priority!==undefined&&!PRIORITIES.includes(x.priority))||!object(x.scope)||(x.scope.kind==="streams"?(!ids(x.scope.streamIds)||x.scope.streamIds.some(v=>!streamIds.has(v))):x.scope.kind!=="project")||!ids(x.relatedTaskIds)||x.relatedTaskIds.some(v=>!taskIds.has(v))))return"Milestone structure is invalid.";
 const actionIds:string[]=[];if(state.risks.some(x=>{if(!identity(x,"RISK",p.id)||!text(x.title,true)||!text(x.description??"")||!owner(x.ownerId)||!RISK_STATUSES.includes(x.status)||!RISK_RATINGS.includes(x.probability)||!RISK_RATINGS.includes(x.impact)||x.riskLevel!==calculateRiskLevel(x.probability,x.impact)||!date(x.dueDate)||typeof x.projectWide!=="boolean"||!ids(x.relatedStreamIds)||x.relatedStreamIds.some(v=>!streamIds.has(v))||!ids(x.relatedTaskIds)||x.relatedTaskIds.some(v=>!taskIds.has(v))||!ids(x.relatedMilestoneIds)||x.relatedMilestoneIds.some(v=>!milestoneIds.has(v))||!Array.isArray(x.actions))return true;return x.actions.some(a=>{actionIds.push(a.id);return!object(a)||!id(a.id)||!text(a.description,true)||!(RISK_ACTION_STATUSES as readonly unknown[]).includes(a.status)||!date(a.dueDate)})}))return"Risk structure is invalid.";
 if(state.decisions.some(x=>!identity(x,"DECISION",p.id)||!text(x.title,true)||!text(x.description??"")||!owner(x.ownerId)||!date(x.decisionDate,false)||typeof x.projectWide!=="boolean"||!ids(x.relatedStreamIds)||x.relatedStreamIds.some(v=>!streamIds.has(v))||!ids(x.relatedTaskIds)||x.relatedTaskIds.some(v=>!taskIds.has(v))||!ids(x.relatedMilestoneIds)||x.relatedMilestoneIds.some(v=>!milestoneIds.has(v))||!ids(x.relatedRiskIds)||x.relatedRiskIds.some(v=>!riskIds.has(v))))return"Decision structure is invalid.";
 const refs=new Map<string,Set<string>>([["project",new Set([p.id])],["stream",streamIds],["task",taskIds],["milestone",milestoneIds],["person",ownerIds],["risk",riskIds],["decision",new Set(state.decisions.map(x=>x.id))]]);const ref=(v:unknown)=>object(v)&&typeof v.kind==="string"&&id(v.id)&&refs.get(v.kind)?.has(v.id);
 if(state.relationships.some(x=>!object(x)||!id(x.id)||x.projectId!==p.id||!text(x.type,true)||!ref(x.source)||!ref(x.target)))return"Relationship structure is invalid.";
 if(state.dependencies.some(x=>!object(x)||!id(x.id)||x.projectId!==p.id||!DEPENDENCY_TYPES.includes(x.type)||!object(x.predecessor)||!object(x.successor)||!(["task","milestone"] as const).includes(x.predecessor.kind)||!(["task","milestone"] as const).includes(x.successor.kind)))return"Dependency structure is invalid.";
 const allIds=[p.id,...state.streams.map(x=>x.id),...state.tasks.map(x=>x.id),...state.milestones.map(x=>x.id),...state.people.map(x=>x.id),...state.risks.map(x=>x.id),...state.decisions.map(x=>x.id),...state.relationships.map(x=>x.id),...state.dependencies.map(x=>x.id),...actionIds];if(new Set(allIds).size!==allIds.length)return"Internal IDs are duplicated.";
 const sequenceKeys=["stream","task","milestone","person","risk","decision"] as const;if(!object(state.identifierSequences)||Object.keys(state.identifierSequences).sort().join()!==[...sequenceKeys].sort().join()||sequenceKeys.some(key=>!Number.isSafeInteger(state.identifierSequences[key])||state.identifierSequences[key]<0))return"Identifier sequences are invalid.";for(const key of sequenceKeys){const prefix=key.toUpperCase();const issued=Math.max(0,...([ ...state.streams,...state.tasks,...state.milestones,...state.people,...state.risks,...state.decisions].filter(x=>x.humanId.startsWith(prefix+"-")).map(x=>Number(x.humanId.split("-")[1]))));if(state.identifierSequences[key]<issued)return"Identifier sequence is corrupt.";}
 return undefined;
}
